/***************************************************************************
 *            twt_gkmake.h
 *
 *  Tuesday 14-07-2020 01:40:42
 *  Copyright  2006  NSCore-DaniloZannoni
 *  gkmake version : 0.8-5
 *  asyntote@gkript.org
 ***************************************************************************
 *
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place
 *  Suite 330, Boston, MA 02111-1307, USA.
 */

    /*!
        \version   gkmake 0.8-5
        \brief     File generated by gkmake<BR>
                   gkmake is an opensource project release under the terms<BR>
                   of the GNU General Public License v3<BR>
                   Distribuite with GIM static library<BR><BR>
                   http://www.gkript.org<BR>
    */


#ifndef	TWT_GKMAKE_VERSIONING
#define	TWT_GKMAKE_VERSIONING

   #define TWT_AUTHOR                       NSCore-DaniloZannoni
   #define TWT_GKMAKE_TOTAL_BUILD           93
   #define TWT_GKMAKE_BUILD                 82
   #define TWT_GKMAKE_LAST_BUILD            "Tuesday 14-07-2020 01:40:42"
   #define TWT_GKMAKE_RELEASE               "0.8-5"

#endif

